# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_DEAL2MAKE_REQUPDATECACHINGDATA_CACHINGDATATYPE = descriptor.EnumDescriptor(
  name='CachingDataType',
  full_name='Deal2Make_ReqUpdateCachingData.CachingDataType',
  filename='CachingDataType',
  values=[
    descriptor.EnumValueDescriptor(
      name='OperationRule', index=0, number=1,
      options=None,
      type=None),
  ],
  options=None,
)


_GAME2MAKE_REQCREATECARD = descriptor.Descriptor(
  name='Game2Make_ReqCreateCard',
  full_name='Game2Make_ReqCreateCard',
  filename='CardMaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='jobID', full_name='Game2Make_ReqCreateCard.jobID', index=0,
      number=1, type=6, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userSN', full_name='Game2Make_ReqCreateCard.userSN', index=1,
      number=2, type=6, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='characterSN', full_name='Game2Make_ReqCreateCard.characterSN', index=2,
      number=3, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='characterName', full_name='Game2Make_ReqCreateCard.characterName', index=3,
      number=4, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='categoryNumber', full_name='Game2Make_ReqCreateCard.categoryNumber', index=4,
      number=5, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cardTitle', full_name='Game2Make_ReqCreateCard.cardTitle', index=5,
      number=6, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cardBody', full_name='Game2Make_ReqCreateCard.cardBody', index=6,
      number=7, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_GAME2MAKE_RESCREATECARD = descriptor.Descriptor(
  name='Game2Make_ResCreateCard',
  full_name='Game2Make_ResCreateCard',
  filename='CardMaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='jobID', full_name='Game2Make_ResCreateCard.jobID', index=0,
      number=1, type=6, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='returnCode', full_name='Game2Make_ResCreateCard.returnCode', index=1,
      number=2, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cardID', full_name='Game2Make_ResCreateCard.cardID', index=2,
      number=3, type=6, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DEAL2MAKE_REQCREATEFORCEDCARD = descriptor.Descriptor(
  name='Deal2Make_ReqCreateForcedCard',
  full_name='Deal2Make_ReqCreateForcedCard',
  filename='CardMaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='serverID', full_name='Deal2Make_ReqCreateForcedCard.serverID', index=0,
      number=1, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='characterID', full_name='Deal2Make_ReqCreateForcedCard.characterID', index=1,
      number=2, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cardTitle', full_name='Deal2Make_ReqCreateForcedCard.cardTitle', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cardBody', full_name='Deal2Make_ReqCreateForcedCard.cardBody', index=3,
      number=4, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='GMID', full_name='Deal2Make_ReqCreateForcedCard.GMID', index=4,
      number=5, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DEAL2MAKE_RESCREATEFORCEDCARD = descriptor.Descriptor(
  name='Deal2Make_ResCreateForcedCard',
  full_name='Deal2Make_ResCreateForcedCard',
  filename='CardMaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='returnCode', full_name='Deal2Make_ResCreateForcedCard.returnCode', index=0,
      number=1, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cardID', full_name='Deal2Make_ResCreateForcedCard.cardID', index=1,
      number=2, type=6, cpp_type=4, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DEAL2MAKE_REQUPDATECACHINGDATA = descriptor.Descriptor(
  name='Deal2Make_ReqUpdateCachingData',
  full_name='Deal2Make_ReqUpdateCachingData',
  filename='CardMaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cachingDataType', full_name='Deal2Make_ReqUpdateCachingData.cachingDataType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _DEAL2MAKE_REQUPDATECACHINGDATA_CACHINGDATATYPE,
  ],
  options=None)


_DEAL2MAKE_RESUPDATECACHINGDATA = descriptor.Descriptor(
  name='Deal2Make_ResUpdateCachingData',
  full_name='Deal2Make_ResUpdateCachingData',
  filename='CardMaker.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='returnCode', full_name='Deal2Make_ResUpdateCachingData.returnCode', index=0,
      number=1, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_DEAL2MAKE_REQUPDATECACHINGDATA.fields_by_name['cachingDataType'].enum_type = _DEAL2MAKE_REQUPDATECACHINGDATA_CACHINGDATATYPE

class Game2Make_ReqCreateCard(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAME2MAKE_REQCREATECARD

class Game2Make_ResCreateCard(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAME2MAKE_RESCREATECARD

class Deal2Make_ReqCreateForcedCard(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEAL2MAKE_REQCREATEFORCEDCARD

class Deal2Make_ResCreateForcedCard(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEAL2MAKE_RESCREATEFORCEDCARD

class Deal2Make_ReqUpdateCachingData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEAL2MAKE_REQUPDATECACHINGDATA

class Deal2Make_ResUpdateCachingData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEAL2MAKE_RESUPDATECACHINGDATA

