# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_SERVEREVENT_EVENT_TYPE = descriptor.EnumDescriptor(
  name='event_type',
  full_name='proto_hub.ServerEvent.event_type',
  filename='event_type',
  values=[
    descriptor.EnumValueDescriptor(
      name='CONNECTED', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=1, number=1,
      options=None,
      type=None),
  ],
  options=None,
)


_REGISTERREQ = descriptor.Descriptor(
  name='RegisterReq',
  full_name='proto_hub.RegisterReq',
  filename='hub.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='server_id', full_name='proto_hub.RegisterReq.server_id', index=0,
      number=1, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event_sub', full_name='proto_hub.RegisterReq.event_sub', index=1,
      number=2, type=7, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_REGISTERANS = descriptor.Descriptor(
  name='RegisterAns',
  full_name='proto_hub.RegisterAns',
  filename='hub.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='proto_hub.RegisterAns.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='server_list', full_name='proto_hub.RegisterAns.server_list', index=1,
      number=2, type=7, cpp_type=3, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SENDMESSAGEREQ = descriptor.Descriptor(
  name='SendMessageReq',
  full_name='proto_hub.SendMessageReq',
  filename='hub.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='job_id', full_name='proto_hub.SendMessageReq.job_id', index=0,
      number=1, type=6, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='server_id', full_name='proto_hub.SendMessageReq.server_id', index=1,
      number=2, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg_buf', full_name='proto_hub.SendMessageReq.msg_buf', index=2,
      number=3, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SENDMESSAGEANS = descriptor.Descriptor(
  name='SendMessageAns',
  full_name='proto_hub.SendMessageAns',
  filename='hub.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='job_id', full_name='proto_hub.SendMessageAns.job_id', index=0,
      number=1, type=6, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='server_id', full_name='proto_hub.SendMessageAns.server_id', index=1,
      number=2, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dest_count', full_name='proto_hub.SendMessageAns.dest_count', index=2,
      number=3, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result', full_name='proto_hub.SendMessageAns.result', index=3,
      number=4, type=8, cpp_type=7, label=2,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_RECVMESSAGEREQ = descriptor.Descriptor(
  name='RecvMessageReq',
  full_name='proto_hub.RecvMessageReq',
  filename='hub.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='server_id', full_name='proto_hub.RecvMessageReq.server_id', index=0,
      number=1, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='job_id', full_name='proto_hub.RecvMessageReq.job_id', index=1,
      number=2, type=6, cpp_type=4, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg_buf', full_name='proto_hub.RecvMessageReq.msg_buf', index=2,
      number=3, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PINGREQ = descriptor.Descriptor(
  name='PingReq',
  full_name='proto_hub.PingReq',
  filename='hub.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PINGANS = descriptor.Descriptor(
  name='PingAns',
  full_name='proto_hub.PingAns',
  filename='hub.proto',
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SERVEREVENT = descriptor.Descriptor(
  name='ServerEvent',
  full_name='proto_hub.ServerEvent',
  filename='hub.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='server_id', full_name='proto_hub.ServerEvent.server_id', index=0,
      number=1, type=7, cpp_type=3, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='event', full_name='proto_hub.ServerEvent.event', index=1,
      number=2, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _SERVEREVENT_EVENT_TYPE,
  ],
  options=None)


_SERVEREVENT.fields_by_name['event'].enum_type = _SERVEREVENT_EVENT_TYPE

class RegisterReq(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERREQ

class RegisterAns(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERANS

class SendMessageReq(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SENDMESSAGEREQ

class SendMessageAns(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SENDMESSAGEANS

class RecvMessageReq(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RECVMESSAGEREQ

class PingReq(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PINGREQ

class PingAns(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PINGANS

class ServerEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVEREVENT

