# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='OpMsg.proto',
  package='op',
  serialized_pb='\n\x0bOpMsg.proto\x12\x02op\"\xd7\x04\n\x05OpMsg\x12\x14\n\x0csender_gusid\x18\x01 \x01(\x07\x12\x16\n\x0ereceiver_gusid\x18\x02 \x01(\x07\x12#\n\x08job_type\x18\x03 \x01(\x0e\x32\x11.op.OpMsg.JobType\x12\x0e\n\x06job_id\x18\x04 \x01(\x06\x12\r\n\x05gufid\x18\x05 \x01(\x07\x12%\n\texec_type\x18\x06 \x01(\x0e\x32\x12.op.OpMsg.ExecType\x12!\n\x19\x63\x61st_target_user_group_sn\x18\x07 \x01(\x07\x12\x13\n\x0bsession_key\x18\x08 \x01(\x0c\x12%\n\targuments\x18\t \x03(\x0b\x32\x12.op.OpMsg.Argument\x12\x13\n\x0bresult_code\x18\n \x01(\x07\x12\x15\n\rresult_scalar\x18\x0b \x01(\x0c\x12(\n\x0bresult_sets\x18\x0c \x03(\x0b\x32\x13.op.OpMsg.ResultSet\x12\x0c\n\x04\x62lob\x18\r \x01(\x0c\x1a\'\n\x08\x41rgument\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x02(\x0c\x1at\n\tResultSet\x12\x14\n\x0c\x63olumn_names\x18\x01 \x03(\x0c\x12%\n\x04rows\x18\x02 \x03(\x0b\x32\x17.op.OpMsg.ResultSet.Row\x12\x13\n\x0btotal_count\x18\x03 \x01(\x07\x1a\x15\n\x03Row\x12\x0e\n\x06values\x18\x01 \x03(\x0c\"0\n\x07JobType\x12\x0b\n\x07REQUEST\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x12\n\n\x06NOTICE\x10\x03\"!\n\x08\x45xecType\x12\x0b\n\x07\x45XECUTE\x10\x01\x12\x08\n\x04\x43\x41ST\x10\x02\x42\x1a\n\x0bop.protocolB\x0bOpMsgProtos')



_OPMSG_JOBTYPE = descriptor.EnumDescriptor(
  name='JobType',
  full_name='op.OpMsg.JobType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='REQUEST', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RESPONSE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NOTICE', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=536,
  serialized_end=584,
)

_OPMSG_EXECTYPE = descriptor.EnumDescriptor(
  name='ExecType',
  full_name='op.OpMsg.ExecType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='EXECUTE', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CAST', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=586,
  serialized_end=619,
)


_OPMSG_ARGUMENT = descriptor.Descriptor(
  name='Argument',
  full_name='op.OpMsg.Argument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='op.OpMsg.Argument.name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='op.OpMsg.Argument.value', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=377,
  serialized_end=416,
)

_OPMSG_RESULTSET_ROW = descriptor.Descriptor(
  name='Row',
  full_name='op.OpMsg.ResultSet.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='values', full_name='op.OpMsg.ResultSet.Row.values', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=513,
  serialized_end=534,
)

_OPMSG_RESULTSET = descriptor.Descriptor(
  name='ResultSet',
  full_name='op.OpMsg.ResultSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='column_names', full_name='op.OpMsg.ResultSet.column_names', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rows', full_name='op.OpMsg.ResultSet.rows', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='total_count', full_name='op.OpMsg.ResultSet.total_count', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_OPMSG_RESULTSET_ROW, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=418,
  serialized_end=534,
)

_OPMSG = descriptor.Descriptor(
  name='OpMsg',
  full_name='op.OpMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sender_gusid', full_name='op.OpMsg.sender_gusid', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='receiver_gusid', full_name='op.OpMsg.receiver_gusid', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='job_type', full_name='op.OpMsg.job_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='job_id', full_name='op.OpMsg.job_id', index=3,
      number=4, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gufid', full_name='op.OpMsg.gufid', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='exec_type', full_name='op.OpMsg.exec_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cast_target_user_group_sn', full_name='op.OpMsg.cast_target_user_group_sn', index=6,
      number=7, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='session_key', full_name='op.OpMsg.session_key', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='arguments', full_name='op.OpMsg.arguments', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result_code', full_name='op.OpMsg.result_code', index=9,
      number=10, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result_scalar', full_name='op.OpMsg.result_scalar', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result_sets', full_name='op.OpMsg.result_sets', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='blob', full_name='op.OpMsg.blob', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_OPMSG_ARGUMENT, _OPMSG_RESULTSET, ],
  enum_types=[
    _OPMSG_JOBTYPE,
    _OPMSG_EXECTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=619,
)


_OPMSG_ARGUMENT.containing_type = _OPMSG;
_OPMSG_RESULTSET_ROW.containing_type = _OPMSG_RESULTSET;
_OPMSG_RESULTSET.fields_by_name['rows'].message_type = _OPMSG_RESULTSET_ROW
_OPMSG_RESULTSET.containing_type = _OPMSG;
_OPMSG.fields_by_name['job_type'].enum_type = _OPMSG_JOBTYPE
_OPMSG.fields_by_name['exec_type'].enum_type = _OPMSG_EXECTYPE
_OPMSG.fields_by_name['arguments'].message_type = _OPMSG_ARGUMENT
_OPMSG.fields_by_name['result_sets'].message_type = _OPMSG_RESULTSET
_OPMSG_JOBTYPE.containing_type = _OPMSG;
_OPMSG_EXECTYPE.containing_type = _OPMSG;

class OpMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Argument(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _OPMSG_ARGUMENT
    
    # @@protoc_insertion_point(class_scope:op.OpMsg.Argument)
  
  class ResultSet(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    
    class Row(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _OPMSG_RESULTSET_ROW
      
      # @@protoc_insertion_point(class_scope:op.OpMsg.ResultSet.Row)
    DESCRIPTOR = _OPMSG_RESULTSET
    
    # @@protoc_insertion_point(class_scope:op.OpMsg.ResultSet)
  DESCRIPTOR = _OPMSG
  
  # @@protoc_insertion_point(class_scope:op.OpMsg)

# @@protoc_insertion_point(module_scope)
